
"""
Plume environmental impact and risk scoring module for the Carbon Mapper QGIS plugin.

This module reads plume polygon layers generated by the hotspot analysis workflow,
uses existing CH4 intensity attributes when available, calculates missing zonal
statistics if needed, assigns impact scores and risk classes to each plume, and
writes a concise environmental impact report for prioritizing plume review.
"""

import os
from datetime import datetime

import processing

from qgis.core import (
    QgsProject,
    QgsMapLayerType,
    QgsDistanceArea,
)
from qgis.PyQt.QtWidgets import (
    QMessageBox,
    QComboBox,
    QLineEdit,
    QTextEdit,
    QFileDialog,
    QGroupBox,
)


class PlumeEnvironmentalAnalysisManager:
    def __init__(self, plugin):
        """
        Manages plume environmental impact analysis operations for the plugin.
        :param plugin: Main QGIS plugin instance.
        """
        self.plugin = plugin

    def refresh_plume_layers(self, *args):
        """Scans active QGIS project layers and fills the vector combobox in the impact panel."""
        vector_combo = self.plugin.findChild(QComboBox, "analysis_vector_combo")
        if not vector_combo:
            group_box_ei = getattr(self.plugin, "group_box_ei", None) or self.plugin.findChild(QGroupBox, "group_box_ei")
            if group_box_ei:
                vector_combo = group_box_ei.findChild(QComboBox, "analysis_vector_combo")

        if vector_combo is None:
            print("[Carbon Mapper Plume] analysis_vector_combo was not found in the interface.")
            return

        current_vector_id = vector_combo.currentData()
        vector_combo.blockSignals(True)
        vector_combo.clear()

        layers = QgsProject.instance().mapLayers().values()
        vector_count = 0
        vector_index_to_restore = -1

        for layer in layers:
            if layer and layer.isValid() and layer.type() == QgsMapLayerType.VectorLayer:
                layer_name = layer.name()
                if "OpenStreetMap" in layer_name or "Google" in layer_name:
                    continue

                vector_combo.addItem(layer_name, layer.id())
                if current_vector_id and layer.id() == current_vector_id:
                    vector_index_to_restore = vector_count
                vector_count += 1

        if vector_count == 0:
            vector_combo.addItem("-- There is no vector layer in the project --", None)
        elif vector_index_to_restore != -1:
            vector_combo.setCurrentIndex(vector_index_to_restore)
        else:
            vector_combo.setCurrentIndex(0)

        vector_combo.blockSignals(False)
        vector_combo.update()

    def browse_output_directory_ei(self):
        output_input_ei = self.plugin.findChild(QLineEdit, "analysis_output_input_ei")
        if not output_input_ei:
            group_box_ei = getattr(self.plugin, "group_box_ei", None) or self.plugin.findChild(QGroupBox, "group_box_ei")
            if group_box_ei:
                output_input_ei = group_box_ei.findChild(QLineEdit, "analysis_output_input_ei")

        if not output_input_ei:
            QMessageBox.critical(self.plugin, "UI Error", "Could not find 'analysis_output_input_ei' line edit!")
            return

        selected_dir_ei = QFileDialog.getExistingDirectory(self.plugin, "Select Output Directory for Environmental Impact")
        if selected_dir_ei:
            output_input_ei.setText(selected_dir_ei)

    def _field_exists(self, layer, field_name):
        return layer.fields().indexFromName(field_name) != -1

    def _safe_float(self, value, default=0.0):
        try:
            if value is None:
                return default
            return float(value)
        except (TypeError, ValueError):
            return default

    def _safe_int(self, value, default=0):
        try:
            if value is None:
                return default
            return int(value)
        except (TypeError, ValueError):
            return default

    def _classify_area(self, area_m2):
        if area_m2 >= 100000:
            return "Large"
        if area_m2 >= 25000:
            return "Medium"
        return "Small"

    def _classify_intensity(self, ch4_max):
        if ch4_max >= 5000:
            return "Very High"
        if ch4_max >= 2500:
            return "High"
        if ch4_max >= 1200:
            return "Moderate"
        return "Low"

    def _classify_signal(self, ch4_sum):
        if ch4_sum >= 500000:
            return "Very High"
        if ch4_sum >= 150000:
            return "High"
        if ch4_sum >= 50000:
            return "Moderate"
        return "Low"

    def _risk_from_score(self, score):
        if score >= 9:
            return "Critical"
        if score >= 6:
            return "High"
        if score >= 3:
            return "Moderate"
        return "Low"

    def _priority_from_risk(self, risk_level):
        priority_map = {
            "Critical": "Immediate Review",
            "High": "High Priority",
            "Moderate": "Routine Review",
            "Low": "Low Priority",
        }
        return priority_map.get(risk_level, "Routine Review")

    def _calculate_risk_score(self, area_m2, ch4_mean, ch4_max, ch4_sum, pixel_count):
        score = 0

        if ch4_max >= 5000:
            score += 3
        elif ch4_max >= 2500:
            score += 2
        elif ch4_max >= 1200:
            score += 1

        if ch4_mean >= 2500:
            score += 3
        elif ch4_mean >= 1500:
            score += 2
        elif ch4_mean >= 1000:
            score += 1

        if ch4_sum >= 500000:
            score += 3
        elif ch4_sum >= 150000:
            score += 2
        elif ch4_sum >= 50000:
            score += 1

        if area_m2 >= 100000:
            score += 2
        elif area_m2 >= 25000:
            score += 1

        if pixel_count >= 100:
            score += 1

        return score

    def _ensure_impact_fields(self, vector_layer):
        required_fields = {
            "impact_scr": "integer",
            "risk_level": "string",
            "priority": "string",
            "area_class": "string",
            "int_class": "string",
            "sig_class": "string",
        }

        missing_fields = [
            name for name in required_fields
            if vector_layer.fields().indexFromName(name) == -1
        ]

        if not missing_fields:
            return

        from qgis.core import QgsField
        from qgis.PyQt.QtCore import QVariant

        fields_to_add = []
        for field_name in missing_fields:
            field_type = required_fields[field_name]
            if field_type == "integer":
                fields_to_add.append(QgsField(field_name, QVariant.Int))
            else:
                fields_to_add.append(QgsField(field_name, QVariant.String, len=32))

        vector_layer.dataProvider().addAttributes(fields_to_add)
        vector_layer.updateFields()

    def _ensure_ch4_statistics(self, raster_layer, vector_layer):
        """
        Reuses ch4_* fields generated by the hotspot analysis when they already exist.
        If they are missing, calculates compatible zonal statistics from the selected raster.
        """
        has_hotspot_stats = (
            self._field_exists(vector_layer, "ch4_count")
            and self._field_exists(vector_layer, "ch4_sum")
            and self._field_exists(vector_layer, "ch4_mean")
            and self._field_exists(vector_layer, "ch4_max")
        )

        if has_hotspot_stats:
            return "existing_ch4_fields"

        if raster_layer is None or not raster_layer.isValid():
            return "missing"

        params = {
            "INPUT": vector_layer,
            "INPUT_VECTOR": vector_layer,
            "INPUT_RASTER": raster_layer,
            "RASTER_INPUT": raster_layer,
            "RASTER_BAND": 1,
            "COLUMN_PREFIX": "ch4_",
            "STATISTICS": [0, 1, 2, 6],
            "OUTPUT": "TEMPORARY_OUTPUT",
        }

        try:
            processing.run("native:zonalstatistics", params)
            vector_layer.triggerRepaint()
            return "calculated_from_raster"
        except Exception:
            params_str = {
                "INPUT": vector_layer.id(),
                "INPUT_VECTOR": vector_layer.id(),
                "INPUT_RASTER": raster_layer.id(),
                "RASTER_INPUT": raster_layer.id(),
                "RASTER_BAND": 1,
                "COLUMN_PREFIX": "ch4_",
                "STATISTICS": [0, 1, 2, 6],
                "OUTPUT": "TEMPORARY_OUTPUT",
            }
            processing.run("native:zonalstatistics", params_str)
            vector_layer.triggerRepaint()
            return "calculated_from_raster"

    def run_environmental_analysis(self):
        raster_combo = self.plugin.findChild(QComboBox, "analysis_raster_combo")
        if not raster_combo:
            group_box_hotspot = getattr(self.plugin, "group_box_hotspot", None) or self.plugin.findChild(QGroupBox, "group_box_hotspot")
            if group_box_hotspot:
                raster_combo = group_box_hotspot.findChild(QComboBox, "analysis_raster_combo")

        vector_combo = self.plugin.findChild(QComboBox, "analysis_vector_combo")
        output_input_ei = self.plugin.findChild(QLineEdit, "analysis_output_input_ei")
        report_txt_ei = self.plugin.findChild(QTextEdit, "analysis_report_txt_ei")

        group_box_ei = getattr(self.plugin, "group_box_ei", None) or self.plugin.findChild(QGroupBox, "group_box_ei")
        if group_box_ei:
            if not vector_combo:
                vector_combo = group_box_ei.findChild(QComboBox, "analysis_vector_combo")
            if not output_input_ei:
                output_input_ei = group_box_ei.findChild(QLineEdit, "analysis_output_input_ei")
            if not report_txt_ei:
                report_txt_ei = group_box_ei.findChild(QTextEdit, "analysis_report_txt_ei")

        if not vector_combo or vector_combo.currentIndex() == -1 or vector_combo.currentData() is None:
            QMessageBox.warning(self.plugin, "Analysis Error", "Please select a valid plume vector layer from Impact panel!")
            return

        vector_layer = QgsProject.instance().mapLayer(vector_combo.currentData())
        if not vector_layer or not vector_layer.isValid():
            QMessageBox.critical(self.plugin, "Layer Error", "Selected plume layer is not valid in QGIS Project!")
            return

        raster_layer = None
        if raster_combo and raster_combo.currentIndex() != -1 and raster_combo.currentData() is not None:
            raster_layer = QgsProject.instance().mapLayer(raster_combo.currentData())

        output_dir = output_input_ei.text().strip() if output_input_ei else ""
        if not output_dir or not os.path.exists(output_dir):
            QMessageBox.warning(self.plugin, "Validation Error", "Please select a valid output directory using 'Browse' in the Impact panel!")
            return

        if report_txt_ei:
            report_txt_ei.setText(
                "Running Plume Risk / Environmental Impact Analysis...\n"
                "Reading plume geometry and CH4 intensity attributes..."
            )
            report_txt_ei.repaint()

        try:
            stats_source = self._ensure_ch4_statistics(raster_layer, vector_layer)
            if stats_source == "missing":
                QMessageBox.warning(
                    self.plugin,
                    "Missing CH4 Statistics",
                    "The selected plume layer does not contain ch4_* fields, and no valid raster layer is available to calculate them."
                )
                return

            required_ch4_fields = ["ch4_count", "ch4_sum", "ch4_mean", "ch4_max"]
            missing_ch4_fields = [
                field_name for field_name in required_ch4_fields
                if not self._field_exists(vector_layer, field_name)
            ]

            if missing_ch4_fields:
                QMessageBox.critical(
                    self.plugin,
                    "Missing Fields",
                    "CH4 statistics could not be prepared. Missing fields:\n" + ", ".join(missing_ch4_fields)
                )
                return

            self._ensure_impact_fields(vector_layer)

            d_area = QgsDistanceArea()
            d_area.setSourceCrs(vector_layer.crs(), QgsProject.instance().transformContext())
            d_area.setEllipsoid(QgsProject.instance().ellipsoid())

            field_indexes = {
                "impact_scr": vector_layer.fields().indexFromName("impact_scr"),
                "risk_level": vector_layer.fields().indexFromName("risk_level"),
                "priority": vector_layer.fields().indexFromName("priority"),
                "area_class": vector_layer.fields().indexFromName("area_class"),
                "int_class": vector_layer.fields().indexFromName("int_class"),
                "sig_class": vector_layer.fields().indexFromName("sig_class"),
            }

            risk_counts = {
                "Low": 0,
                "Moderate": 0,
                "High": 0,
                "Critical": 0,
            }

            total_area_m2 = 0.0
            total_ch4_sum = 0.0
            plume_count = 0

            highest_peak = {
                "plume_id": None,
                "value": 0.0,
            }
            largest_signal = {
                "plume_id": None,
                "value": 0.0,
            }
            highest_score = {
                "plume_id": None,
                "score": -1,
                "risk": "Low",
            }

            updates = {}

            for feature in vector_layer.getFeatures():
                geom = feature.geometry()
                if geom and not geom.isEmpty():
                    area_m2 = d_area.measureArea(geom)
                else:
                    area_m2 = 0.0

                plume_id = feature["plume_id"] if self._field_exists(vector_layer, "plume_id") else feature.id()
                pixel_count = self._safe_int(feature["ch4_count"], 0)
                ch4_sum = self._safe_float(feature["ch4_sum"], 0.0)
                ch4_mean = self._safe_float(feature["ch4_mean"], 0.0)
                ch4_max = self._safe_float(feature["ch4_max"], 0.0)

                if ch4_sum < 0:
                    ch4_sum = 0.0
                if ch4_mean < 0:
                    ch4_mean = 0.0
                if ch4_max < 0:
                    ch4_max = 0.0

                impact_score = self._calculate_risk_score(
                    area_m2,
                    ch4_mean,
                    ch4_max,
                    ch4_sum,
                    pixel_count,
                )
                risk_level = self._risk_from_score(impact_score)
                priority = self._priority_from_risk(risk_level)
                area_class = self._classify_area(area_m2)
                intensity_class = self._classify_intensity(ch4_max)
                signal_class = self._classify_signal(ch4_sum)

                updates[feature.id()] = {
                    field_indexes["impact_scr"]: impact_score,
                    field_indexes["risk_level"]: risk_level,
                    field_indexes["priority"]: priority,
                    field_indexes["area_class"]: area_class,
                    field_indexes["int_class"]: intensity_class,
                    field_indexes["sig_class"]: signal_class,
                }

                plume_count += 1
                total_area_m2 += area_m2
                total_ch4_sum += ch4_sum
                risk_counts[risk_level] += 1

                if ch4_max > highest_peak["value"]:
                    highest_peak["value"] = ch4_max
                    highest_peak["plume_id"] = plume_id

                if ch4_sum > largest_signal["value"]:
                    largest_signal["value"] = ch4_sum
                    largest_signal["plume_id"] = plume_id

                if impact_score > highest_score["score"]:
                    highest_score["score"] = impact_score
                    highest_score["plume_id"] = plume_id
                    highest_score["risk"] = risk_level

            vector_layer.dataProvider().changeAttributeValues(updates)
            vector_layer.updateFields()
            vector_layer.triggerRepaint()

        except Exception as e:
            QMessageBox.critical(self.plugin, "Analysis Failure", f"Plume impact scoring failed:\n{str(e)}")
            return

        raster_name = raster_layer.name() if raster_layer and raster_layer.isValid() else "Not used"
        stats_source_text = {
            "existing_ch4_fields": "Existing plume CH4 attributes",
            "calculated_from_raster": "Calculated from selected raster",
            "missing": "Unavailable",
        }.get(stats_source, stats_source)

        report_lines = [
            "==================================================",
            "     CARBON MAPPER - PLUME IMPACT REPORT",
            "==================================================",
            "",
            "Input Layers:",
            f"- Plume layer: {vector_layer.name()}",
            f"- Raster baseline: {raster_name}",
            f"- CH4 statistics source: {stats_source_text}",
            "",
            "Impact Summary:",
            f"- Analyzed plume objects: {plume_count}",
            f"- Total affected area: {(total_area_m2 / 1_000_000.0):.4f} km2",
            f"- Total CH4 signal inside plumes: {total_ch4_sum:.4f}",
            "",
            "Risk Classes:",
            f"- Low: {risk_counts['Low']}",
            f"- Moderate: {risk_counts['Moderate']}",
            f"- High: {risk_counts['High']}",
            f"- Critical: {risk_counts['Critical']}",
            "",
            "Priority Plumes:",
            f"- Highest peak plume ID: {highest_peak['plume_id']}",
            f"- Highest peak value: {highest_peak['value']:.4f} ppm/m",
            f"- Largest total signal plume ID: {largest_signal['plume_id']}",
            f"- Largest total signal value: {largest_signal['value']:.4f}",
            f"- Highest impact score plume ID: {highest_score['plume_id']}",
            f"- Highest impact score: {highest_score['score']} ({highest_score['risk']})",
            "",
            "New Fields Added / Updated:",
            "- impact_scr",
            "- risk_level",
            "- priority",
            "- area_class",
            "- int_class",
            "- sig_class",
            "",
            "Status: COMPLETED",
            "==================================================",
        ]

        full_report = "\n".join(report_lines)

        if report_txt_ei:
            report_txt_ei.setText(full_report)

        safe_layer_name = "".join([c if c.isalnum() else "_" for c in vector_layer.name()])
        run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_path = os.path.join(output_dir, f"Plume_Impact_Report_{safe_layer_name}_{run_id}.txt")

        try:
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(full_report)
            QMessageBox.information(self.plugin, "Analysis Success", f"Environmental Impact Report saved successfully to:\n{report_path}")
        except Exception as e:
            QMessageBox.critical(self.plugin, "File Error", f"Could not save environmental report: {str(e)}")